### ISSUE TITLE
export ssn with dist matrix and additive function

### ISSUE THREAD

**Issue by alaindanet** [MiKatt/openSTARS#9]
Hi,

I am currently doing intensive interpolation of stream datas with the SSN package.
I currently perform at each spatial area the loading of one ssn object and have to compute the additive function and the distance matrix. The latter is relatively time consuming.

I wonder if there is an easy way to export the ssn object with the distance matrix and the result of the additive function which are respectively created by `SSN::createDistMat` and `SSN::additive.function`.

Thank you very much.

EDIT:
Actually, I realize that it would be a minor feature.

**Comment by MiKatt** [comment]
Hello,
you mean, you would like to have a function within openSTARS to export the distance matrix and the additive function? I think this would not help much, as it would be based on the same functions from the SSN package you mention. 
I think, `SSN::writeSSN` can save the object once you calculated everything so that there is no need to recalculate it when reloading.

**Comment by alaindanet** [comment]
Thank you!
Yes, I meant saving the updated SSN with the distance matrix and the additive function.
It seems that also save the resulting object in .RData is doing the trick.
